/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Logica.*;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
/**
 *
 * @author SysAdmin
 */
public class agregarPromocion extends javax.swing.JInternalFrame {

    /**
     * Creates new form agregarPromocion
     */
    private DefaultListModel modelo;
    private DefaultListModel modelo2;
    private IControladorPromociones icpromo;
    private IControladorProveedores icprov;
    private ArrayList<Integer> precioTotal = new ArrayList();
    private int vueltas = 0;
    private int descuento = 0;
    private int precio = 0;
    public agregarPromocion(IControladorPromociones icopromo, IControladorProveedores icprov) {
        initComponents();
        SpinnerNumberModel modelospn = new SpinnerNumberModel(0,0,100,1);
        spnDescuento.setModel(modelospn);
        modelo = new DefaultListModel();
        modelo2 = new DefaultListModel();
        this.txtPrecioPromo.setEditable(false);
        listaServicios.setModel(modelo);
        listaServiciosElegidos.setModel(modelo2);
        this.txtPrecioPromo.setText("0");
        this.icpromo = icopromo;
        this.icprov = icprov;
        filldb();
        fillLista();
    }
    
    
    
    
    
    public void filldb(){
        int tamProve= 0;
        int inicio=0;
        ArrayList<DataProveedor> prove = new ArrayList();
        try {
            prove = icprov.getProveedores();
        } catch (SQLException ex) {
            Logger.getLogger(agregarPromocion.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(agregarPromocion.class.getName()).log(Level.SEVERE, null, ex);
        }
        tamProve = prove.size();
        for(inicio=0;inicio<tamProve;inicio++){
            this.dbProveedores.addItem(prove.get(inicio).getNombreEmpresa());
        }
    }
    
    
    public void fillLista(){
        modelo.removeAllElements();
        modelo2.removeAllElements();
        ArrayList<DataServicio> servicios = new ArrayList();
        try {
            servicios = this.icprov.getServiciosProveedor(this.dbProveedores.getItemAt(dbProveedores.getSelectedIndex()));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(agregarPromocion.class.getName()).log(Level.SEVERE, null, ex);
        }
        int tamanio = servicios.size();
        int inicio = 0;
        for(inicio=0;inicio<tamanio;inicio++){
            String NombreS;
            NombreS = servicios.get(inicio).getNombreServicio();
            int precioS = servicios.get(inicio).getPrecioServicio();
            String componente = NombreS + "-" + String.valueOf(precioS);
            modelo.addElement(componente);
        }
    }
    
    public void precioPromo(){
        
        descuento = (Integer)this.spnDescuento.getValue();
        
        precio = icpromo.calcularPrecio(precioTotal, descuento);
        
        this.txtPrecioPromo.setText(String.valueOf(precio));
    }
    public void clearCamps(){
        this.txtNombrePromo.setText("");
        this.txtPrecioPromo.setText("0");
        modelo2.removeAllElements();
        this.spnDescuento.setValue(0);
        fillLista();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionarProveedorPanel = new javax.swing.JPanel();
        dbProveedores = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        agregarPromocionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaServicios = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaServiciosElegidos = new javax.swing.JList<>();
        agregarServicio = new javax.swing.JButton();
        quitarServicio = new javax.swing.JButton();
        txtNombrePromo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioPromo = new javax.swing.JTextField();
        spnDescuento = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        agregarPromo = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();

        setClosable(true);

        dbProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbProveedoresActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione el nombre del proveedor del servicio");

        javax.swing.GroupLayout seleccionarProveedorPanelLayout = new javax.swing.GroupLayout(seleccionarProveedorPanel);
        seleccionarProveedorPanel.setLayout(seleccionarProveedorPanelLayout);
        seleccionarProveedorPanelLayout.setHorizontalGroup(
            seleccionarProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarProveedorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(seleccionarProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dbProveedores, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(seleccionarProveedorPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        seleccionarProveedorPanelLayout.setVerticalGroup(
            seleccionarProveedorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(seleccionarProveedorPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dbProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(listaServicios);

        jScrollPane2.setViewportView(listaServiciosElegidos);

        agregarServicio.setText("Agregar");
        agregarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarServicioActionPerformed(evt);
            }
        });

        quitarServicio.setText("Quitar");
        quitarServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitarServicioActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre de la promoción");

        jLabel3.setText("Precio de la promoción");

        spnDescuento.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnDescuentoStateChanged(evt);
            }
        });

        jLabel4.setText("Descuento de la promoción");

        jLabel5.setText("Nombre - Precio");

        jLabel6.setText("Elegidos");

        jLabel7.setText("%");

        agregarPromo.setText("Aceptar");
        agregarPromo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPromoActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout agregarPromocionPanelLayout = new javax.swing.GroupLayout(agregarPromocionPanel);
        agregarPromocionPanel.setLayout(agregarPromocionPanelLayout);
        agregarPromocionPanelLayout.setHorizontalGroup(
            agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarPromocionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarPromocionPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(agregarServicio)
                            .addComponent(quitarServicio)))
                    .addGroup(agregarPromocionPanelLayout.createSequentialGroup()
                        .addComponent(spnDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addComponent(txtNombrePromo)
                        .addComponent(txtPrecioPromo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap())
            .addGroup(agregarPromocionPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(agregarPromo)
                .addGap(42, 42, 42)
                .addComponent(cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        agregarPromocionPanelLayout.setVerticalGroup(
            agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarPromocionPanelLayout.createSequentialGroup()
                .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarPromocionPanelLayout.createSequentialGroup()
                        .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtNombrePromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecioPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(agregarPromocionPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(agregarServicio)
                        .addGap(54, 54, 54)
                        .addComponent(quitarServicio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(agregarPromocionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarPromo)
                    .addComponent(cancelar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccionarProveedorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(agregarPromocionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(seleccionarProveedorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(agregarPromocionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbProveedoresActionPerformed
        
        this.spnDescuento.setValue(0);
        
        this.txtPrecioPromo.setText("0");
        
        fillLista();
    }//GEN-LAST:event_dbProveedoresActionPerformed

    private void agregarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarServicioActionPerformed
        // TODO add your handling code here:
        
        if(this.listaServicios.getSelectedValue()==null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un servicio de la lsita de servicios.", "ALERTA", JOptionPane.WARNING_MESSAGE);
        }
        else{
        precio = icpromo.getPrecio(listaServicios.getSelectedValue());
        
        precioTotal.add(precio);
        
        precioPromo();
        
        modelo2.addElement(listaServicios.getSelectedValue());
        
        modelo.removeElement(listaServicios.getSelectedValue());
        }
    }//GEN-LAST:event_agregarServicioActionPerformed

    private void quitarServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitarServicioActionPerformed
        // TODO add your handling code here:
        
        if(this.listaServiciosElegidos.getSelectedValue()==null){
            JOptionPane.showMessageDialog(null, "Debe seleccionar un servicio de la lista de servicios elegidos.", "ALERTA", JOptionPane.WARNING_MESSAGE);
        }
        else{
        int precioAQuitar = 0;
        
        precioAQuitar = this.icpromo.getPrecio(listaServiciosElegidos.getSelectedValue());
        
        precioTotal.remove(precioTotal.indexOf(precioAQuitar));
        
        precioPromo();
        
        modelo.addElement(listaServiciosElegidos.getSelectedValue());
        
        modelo2.removeElement(listaServiciosElegidos.getSelectedValue());
        }
        
    }//GEN-LAST:event_quitarServicioActionPerformed

    private void spnDescuentoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnDescuentoStateChanged
        // TODO add your handling code here:
        precioPromo();
    }//GEN-LAST:event_spnDescuentoStateChanged

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void agregarPromoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPromoActionPerformed
        // TODO add your handling code here:
        boolean errores = false;
        int resultadoPromocion = 0;
        int resultadoServiciosPromocion = 0;
        if(this.txtNombrePromo.getText().isEmpty() && errores == false){
            JOptionPane.showMessageDialog(null, "El nombre de la promocion no puede ser vacío.", "ALERTA", JOptionPane.WARNING_MESSAGE);
            errores = true;
        }
        if(this.listaServiciosElegidos.getModel().getSize()==0 && errores == false ){
            JOptionPane.showMessageDialog(null, "Una promocion debe contener al menos un servicio.", "ALERTA", JOptionPane.WARNING_MESSAGE);
            errores = true;
        }
        if(errores == false){            
            try {
                resultadoPromocion = this.icpromo.agregarPromocion(this.precio, this.txtNombrePromo.getText(), this.descuento);
                for(vueltas = 0; vueltas < this.listaServiciosElegidos.getModel().getSize(); vueltas ++){
                    String servicio = this.icpromo.getNombreServicio(this.listaServiciosElegidos.getModel().getElementAt(vueltas));
                    resultadoServiciosPromocion = this.icpromo.agregarServiciosPromocion(this.txtNombrePromo.getText(),servicio,this.dbProveedores.getSelectedItem().toString());   
                }
                if(resultadoPromocion == 1 && resultadoServiciosPromocion == this.listaServiciosElegidos.getModel().getSize()-1){
                    JOptionPane.showMessageDialog(null, "La promoción se ha agregado correctamente.", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                }
                clearCamps();
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error con la base de datos. Por favor intente denuevo mas tarde.", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_agregarPromoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPromo;
    private javax.swing.JPanel agregarPromocionPanel;
    private javax.swing.JButton agregarServicio;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> dbProveedores;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaServicios;
    private javax.swing.JList<String> listaServiciosElegidos;
    private javax.swing.JButton quitarServicio;
    private javax.swing.JPanel seleccionarProveedorPanel;
    private javax.swing.JSpinner spnDescuento;
    private javax.swing.JTextField txtNombrePromo;
    private javax.swing.JTextField txtPrecioPromo;
    // End of variables declaration//GEN-END:variables
}
