/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Logica.*;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/**
 *
 * @author Mauro
 */
public class agregarPromocion extends javax.swing.JInternalFrame {
    private IControladorPromociones icprom;
    private IControladorProveedores icprov;
    private String Seleccionado;
    /**
     * Creates new form agregarPromocion
     */
    public agregarPromocion(IControladorPromociones icprom,IControladorProveedores icprov) {
        initComponents();
        this.icprom = icprom;
        this.icprov = icprov;
        this.setLocation(400, 130);
        DefaultListModel modeloElegir = new DefaultListModel();
        listaServiciosElegidos.setModel(modeloElegir);
        getServicios();
    }
    public boolean servicioRepetido(DefaultListModel modelo, String Seleccionado){
        boolean repetido = false;
        //System.out.println(modelo.getSize());
        DefaultListModel modeloServicios = (DefaultListModel)listaServicios.getModel();
        for(int i = 0; i < modelo.getSize(); i++){
            if(modelo.getElementAt(i).equals(Seleccionado))
                repetido = true;
        }

        return repetido;
    }
    
    public void getServicios(){
        int inicio = 0;
        ArrayList<DataServicio> allServicios = new ArrayList();
        try {
            allServicios = icprov.getServicios();
            DefaultListModel lista = new DefaultListModel();
            int tamanio = allServicios.size();
            for(inicio = 0; inicio<tamanio;inicio ++){
                lista.addElement(allServicios.get(inicio).getNombreServicio()+", "+allServicios.get(inicio).getPrecioServicio()+", "+allServicios.get(inicio).getNombreProveedor());
            }
            this.listaServicios.setModel(lista);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Hay un problema de conexión con la base de datos, por lo que no fue posible completar la acción", "ERROR", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(agregarPromocion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregarPromoPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaServicios = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaServiciosElegidos = new javax.swing.JList<>();
        elegirServicio = new javax.swing.JButton();
        eliminarServicio = new javax.swing.JButton();
        nombrePromocion = new javax.swing.JTextField();
        descuentoPromocion = new javax.swing.JTextField();
        precioTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        agregarPromocion = new javax.swing.JButton();
        salir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Agregar Promoción");

        jScrollPane1.setViewportView(listaServicios);

        jScrollPane2.setViewportView(listaServiciosElegidos);

        elegirServicio.setText("Agregar");
        elegirServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elegirServicioActionPerformed(evt);
            }
        });

        eliminarServicio.setText("Quitar");

        jLabel1.setText("Nombre de la promoción.");

        jLabel2.setText("Descuento de la promoción");

        jLabel3.setText("Precio de la promoción");

        agregarPromocion.setText("Agregar");
        agregarPromocion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPromocionActionPerformed(evt);
            }
        });

        salir.setText("Cancelar");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Servicio - Precio - Proveedor");

        javax.swing.GroupLayout agregarPromoPanelLayout = new javax.swing.GroupLayout(agregarPromoPanel);
        agregarPromoPanel.setLayout(agregarPromoPanelLayout);
        agregarPromoPanelLayout.setHorizontalGroup(
            agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarPromoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(agregarPromoPanelLayout.createSequentialGroup()
                        .addComponent(agregarPromocion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir))
                    .addComponent(precioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(descuentoPromocion)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(nombrePromocion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, agregarPromoPanelLayout.createSequentialGroup()
                                .addComponent(elegirServicio)
                                .addGap(13, 13, 13)
                                .addComponent(eliminarServicio)
                                .addGap(16, 16, 16)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(23, 23, 23))
        );
        agregarPromoPanelLayout.setVerticalGroup(
            agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(agregarPromoPanelLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(agregarPromoPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(elegirServicio)
                            .addComponent(eliminarServicio))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(agregarPromoPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(nombrePromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(descuentoPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(precioTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(agregarPromoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarPromocion)
                            .addComponent(salir))
                        .addGap(97, 97, 97))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(agregarPromoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(agregarPromoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_salirActionPerformed

    private void elegirServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elegirServicioActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = new DefaultListModel();
        modelo = (DefaultListModel)listaServiciosElegidos.getModel();
        Seleccionado = listaServicios.getSelectedValue();
        if(!servicioRepetido(modelo, Seleccionado)){
            String valor = listaServicios.getSelectedValue();
            modelo.addElement(valor);
            listaServiciosElegidos.setModel(modelo);
        }else{
            JOptionPane.showMessageDialog(this, "El servicio ya forma parte de la promoción.", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_elegirServicioActionPerformed

    private void agregarPromocionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPromocionActionPerformed
        // TODO add your handling code here:
        DefaultListModel modelo = new DefaultListModel();
        modelo = (DefaultListModel) listaServiciosElegidos.getModel();
        if(modelo.size()<1){
            JOptionPane.showMessageDialog(this, "Una promoción debe contener al menos un servicio. ", "ADVERTENCIA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_agregarPromocionActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel agregarPromoPanel;
    private javax.swing.JButton agregarPromocion;
    private javax.swing.JTextField descuentoPromocion;
    private javax.swing.JButton elegirServicio;
    private javax.swing.JButton eliminarServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listaServicios;
    private javax.swing.JList<String> listaServiciosElegidos;
    private javax.swing.JTextField nombrePromocion;
    private javax.swing.JTextField precioTotal;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
