/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;
import Logica.*;
import Logica.IControladorClientes;
import java.awt.Dimension;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author chaos
 */
public class ifrmActualizarEstadoReserva extends javax.swing.JInternalFrame {
 
    private IControladorClientes iccli;
    /**
     * Creates new form ifrmActualizarEstadoReserva
     */
    public ifrmActualizarEstadoReserva() {
        initComponents();
    }
      
    private String[] columnas = {"Numero", "Estado"};
    private DefaultTableModel datosPromocionServ = new DefaultTableModel(null, columnas) {
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };
    public ifrmActualizarEstadoReserva(IControladorClientes iccli){
        initComponents();
         setTitle("Actualizar estado reserva");
        Dimension tamanioVentana = this.getSize();
        setLocation((1400 - tamanioVentana.width)/2, (600 - tamanioVentana.height)/2);
        
        this.iccli = iccli;
        DefaultTableModel model=  new DefaultTableModel(null, columnas);
    
        try{
            ArrayList<DataReserva> numRes= this.iccli.verInfoReserva(); 
            //System.out.println(numRes.size());
            
        for(int i =0;i<numRes.size();i++){
//            DataReserva resAux=new DataReserva();
//            resAux.setNumero(numRes.get(i).getNumero());
//            resAux.setEstado(numRes.get(i).getEstado());
            Object[] fila = {numRes.get(i).getNumero(), numRes.get(i)};
            model.addRow(fila);
            
        }
         //uuh a ver
         //viste que en el otro trae bien xD
         //sisi, esta trayendo una fila x el nro y otra x el estado
         //mauro, x en al otra aparecen esos ods atrbituos sueltos? los agregaste?
         //no, se ve que se cambio algo de la otra función, esperame dejame ver una cosa
         //vs cambiaste alguna funcion de la otra?,aca mira , dejame lleavrte
         tablaRes.setModel(model);
        }catch(Exception e){}
        
        initComponents();
       tablaRes.setModel(model);
       tablaRes.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaRes = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setText("Seleccione reserva:");

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaRes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Numero", "Estado"
            }
        ));
        tablaRes.setAutoscrolls(false);
        tablaRes.setCellSelectionEnabled(true);
        jScrollPane2.setViewportView(tablaRes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(419, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        // TODO add your handling code here:
//        if(listRes.getSelectedIndex() == -1){
//            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna reserva", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
//        }
//        else{
//            String selected =listRes.getSelectedValue();
//            try {
//                DataReserva dtcant =this.iccli.getReserva(selected);
//                if(dtcant.getEstado()!="REGISTRADA"){
//                    JOptionPane.showMessageDialog(this, "El tipo de reserva no es registrada", "Error", JOptionPane.WARNING_MESSAGE);
//                }
//            } catch (Exception e) {
//                Logger.getLogger(ifrmActualizarEstadoReserva.class.getName()).log(Level.SEVERE, null, e);
//            } 
//        }
//        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaRes;
    // End of variables declaration//GEN-END:variables
}
