/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.DataPromocion;
import Logica.DataServicio;
import Logica.IControladorCategorias;
import Logica.IControladorPromociones;
import Logica.IControladorProveedores;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Mauro
 */
public class verInfoPromocion extends javax.swing.JInternalFrame {

    /**
     * Creates new form verInfoPromocion
     */
    private IControladorPromociones icpromo;
    private IControladorProveedores icprov;
    private IControladorCategorias iccat;
    private int vueltas=0;
    private DefaultListModel modelo = new DefaultListModel();
    public verInfoPromocion(IControladorPromociones icpromo,IControladorProveedores icprov, IControladorCategorias iccat) {
        initComponents();
        this.txtDescuento.setEditable(false);
        this.txtPrecioPromo.setEditable(false);
        this.listaServicios.setModel(modelo);
        this.icpromo=icpromo;
        this.iccat = iccat;
        this.icprov = icprov;
        ArrayList<DataPromocion> dPromo = new ArrayList();
        try {
            dPromo = icpromo.getPromociones();
            for (vueltas = 0; vueltas < dPromo.size(); vueltas ++){
                String DB = "aaaa";
                DB = dPromo.get(vueltas).getNombre() + "-" + dPromo.get(vueltas).getProveedor();  
                this.dbPromociones.addItem(DB);                
            }

        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(verInfoPromocion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPromocion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dbPromociones = new javax.swing.JComboBox<>();
        panelInfoPromocion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioPromo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescuento = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaServicios = new javax.swing.JList<>();
        btnVerInfoServicio = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Seleccione el nombre de la Promoción de la cual desea ver información.");

        dbPromociones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbPromocionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPromocionLayout = new javax.swing.GroupLayout(panelPromocion);
        panelPromocion.setLayout(panelPromocionLayout);
        panelPromocionLayout.setHorizontalGroup(
            panelPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPromocionLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPromocionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dbPromociones, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelPromocionLayout.setVerticalGroup(
            panelPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPromocionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(dbPromociones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("Precio de la promoción.");

        jLabel4.setText("Descuento de la promoción.");

        jScrollPane1.setViewportView(listaServicios);

        btnVerInfoServicio.setText("Ver Informacion de servicio");
        btnVerInfoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerInfoServicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInfoPromocionLayout = new javax.swing.GroupLayout(panelInfoPromocion);
        panelInfoPromocion.setLayout(panelInfoPromocionLayout);
        panelInfoPromocionLayout.setHorizontalGroup(
            panelInfoPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPromocionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoPromocionLayout.createSequentialGroup()
                        .addGroup(panelInfoPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(txtPrecioPromo)
                            .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoPromocionLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVerInfoServicio)
                        .addContainerGap())))
        );
        panelInfoPromocionLayout.setVerticalGroup(
            panelInfoPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoPromocionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInfoPromocionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelInfoPromocionLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtPrecioPromo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(txtDescuento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16)
                .addComponent(btnVerInfoServicio)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPromocion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInfoPromocion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPromocion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInfoPromocion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbPromocionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbPromocionesActionPerformed
        // TODO add your handling code here:
        String promocion = "";
        promocion = this.dbPromociones.getItemAt(this.dbPromociones.getSelectedIndex());
        modelo.clear();
        String NombrePromo = "";
        String NombreProv = "";
        
        int i = 0;
        NombrePromo = getNombrePromo(promocion);
        NombreProv = getNombreProv(promocion);
        DataPromocion promo = new DataPromocion();
        ArrayList<DataServicio> servicios = new ArrayList();
        try {
            promo = this.icpromo.getDataPromocion(NombrePromo, NombreProv);
            servicios = this.icpromo.getServiciosPromocion(NombrePromo, NombreProv);
            for(i=0;i<servicios.size();i++){
                modelo.addElement(servicios.get(i).getNombreServicio());
            }
            this.txtDescuento.setText(String.valueOf(promo.getDescuento()));
            this.txtPrecioPromo.setText(String.valueOf(promo.getPrecio()));
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(verInfoPromocion.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_dbPromocionesActionPerformed

    private void btnVerInfoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerInfoServicioActionPerformed
        // TODO add your handling code here:
        String servicio = "";
        servicio = this.listaServicios.getSelectedValue();
        ifrmInformacionServicios info = new ifrmInformacionServicios(this.icprov,this.iccat,servicio);
        getParent().add(info);
        info.setVisible(true);
    }//GEN-LAST:event_btnVerInfoServicioActionPerformed
    public String getNombrePromo(String cadena){
    
        String [] partes = new String[2];

        partes = cadena.split("-");

        String nombre;

        nombre = String.valueOf(partes[0].trim());

        return nombre;
    }
        public String getNombreProv(String cadena){
    
        String [] partes = new String[2];

        partes = cadena.split("-");

        String nombre;

        nombre = String.valueOf(partes[1].trim());

        return nombre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerInfoServicio;
    private javax.swing.JComboBox<String> dbPromociones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaServicios;
    private javax.swing.JPanel panelInfoPromocion;
    private javax.swing.JPanel panelPromocion;
    private javax.swing.JTextField txtDescuento;
    private javax.swing.JTextField txtPrecioPromo;
    // End of variables declaration//GEN-END:variables
}
